### ISSUE TITLE
`pm2 install` vs `npm install`

### ISSUE THREAD

**Issue by IPWright83** [keymetrics/pm2-logrotate#119]
I've a question, on the README it specifically says to use `pm2 install`. I'm really interested to know how this differs from `npm install`?

I ask because somehow I need to be able to package `pm2` update with modules for an offline deployment. Could you shed any light? Thanks

**Comment by Unitech** [comment]
pm2 install is npm install pm2-logrotate + pm2 start pm2-logrotate
It installs that app in the .pm2 folder and auto start it anytime pm2 is alive
For support on offline installs contact us at contact@keymetrics.io, cheers
