### ISSUE TITLE
High memory usage

### ISSUE THREAD

**Issue by DevBrent** [keymetrics/pm2-logrotate#45]
First use-case, ubuntu14.04
pm2-logrotate 2.0.0
PMX version 0.6.8
Global logs size 20.87 GB (yeah, we should probably turn on cleanup)
Files count 8.4K
Memory Usage: 958.6 MB

Second use-case, amazon linux-ami
pm2-logrotate 2.0.0
PMX version 0.6.8
Global logs size 147.11 MB
Files count 836
Memory usage: 579.4 MB

**Comment by vmarchaud** [comment]
Are you using the default configuration ? If not could you please provide the configuration you are using (you can get it by running `pm2 conf`)

**Comment by FredrikSeidl** [comment]
We have the same issue in our environment, also on 2.0.0. Our settings are below

`retain=5`
`max_size=100M`

**Comment by korentsov** [comment]
We have same issue, version 2.2.0, pm2 version 2.4.0

 Module activated
┌───────────────┬─────────┬────────────┬────────┬─────────┬─────┬──────────────┐
│ Module        │ version │ target PID │ status │ restart │ cpu │ memory       │
├───────────────┼─────────┼────────────┼────────┼─────────┼─────┼──────────────┤
│ pm2-logrotate │ 2.2.0   │ N/A        │ online │ 0       │ 0%  │ 251.965 MB   │
└───────────────┴─────────┴────────────┴────────┴─────────┴─────┴──────────────┘
 Use `pm2 show <id|name>` to get more details about an app

Our settings:

== module-db ==
┌───────────────┬───────┐
│ key           │ value │
├───────────────┼───────┤
│ pm2-logrotate │ true  │
└───────────────┴───────┘
== pm2-logrotate ==
┌───────────────┬───────┐
│ key           │ value │
├───────────────┼───────┤
│ max_size      │ 10M   │
│ interval_unit │ mm    │
│ interval      │ 60    │
│ retain        │ 50    │

**Comment by ma-zal** [comment]
I found a memory leak.

You can try my commit with fix: https://github.com/ma-zal/pm2-logrotate/commit/0723af9f9e7fff2dfde2305b2f0d932fe09ad559 (temporary branch fix-unlink-enoent). 

In newer pm2, you can install it by:

`pm2 install ma-zal/pm2-logrotate#fix-unlink-enoent` 

Note: Older PM2 cannot install specific branch (https://github.com/Unitech/pm2/issues/2809)

**Comment by amit777** [comment]
I'm running pm2 2.8.0 with pm2-logrotate 1.2.0.  I think we are experiencing a memory leak with pm2-logrotate. Would our version numbers be consistent with this potential memory leak?

what's the recommended way of getting logrotate 2.x installed with pm2?

**Comment by ipengyo** [comment]
master branch READM.ME  How the recommended version is 2.2?

**Comment by nitrocode** [comment]
@amit777 @ipengyo the current version is 2.4.0. The command you're using in the README is to install a specific version. If you drop the "@2.2.0" from the README command, it installs the latest version. I can see how it's confusing.

**Comment by dskrvk** [comment]
Happened today with pm2@3.5.0 and pm2-logrotate@2.6.0 (latest).

**Comment by Unitech** [comment]
https://github.com/keymetrics/pm2-logrotate/blob/master/package.json#L30
pm2-logrotate is auto restarted in case of usage of more than 500mo

Please upgrade to the latest version, I've also updated the documentation to not display "2.2.0"
